runtime: python27
api_version: 1
threadsafe: yes
service: appwebsite
# env_variables:
#   API_KEY: <API key for projects app engine>

handlers:

  - url: /(.*\.(gif|png|ttf|woff|woff2|eot|svg|jpg|css|js)(|\.map))$
    static_files: dist/loboGameForApp/assets/\1
    upload: dist/loboGameForApp/assets/(.*)(|\.map)

  - url: /(.*)
    static_files: dist/loboGameForApp/index.html
    upload: dist/loboGameForApp/index.html

  - url: /
    static_files: dist/loboGameForApp/index.html
    upload: dist/loboGameForApp/index.html

  - url: /
    static_dir: dist/loboGameForApp 

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE